AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'LocationService'

Resources:
  PatronService:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.handler
      Runtime: python3.10
      Timeout: 10
      Environment:
        Variables:
          LOG_LEVEL: debug
          ENVIRONMENT: qa
      Events:
        ApiPatronPath:
          Type: Api
          Properties:
            Path: "/api/v0.1/locations"
            Method: GET