PLAINTEXT_VARIABLES:
  NYPL_CORE_OBJECTS_BASE_URL: https://nypl-core-objects-mapping-production.s3.amazonaws.com/
  LOG_LEVEL: 'debug'
  S3_BUCKET: locations-mapping-production
  S3_LOCATIONS_FILE: locations.json
  REGION: us-east-1
  REFINERY_API_BASE_URL: "https://refinery.nypl.org/api/nypl/locations/v1.0/locations/"