PLAINTEXT_VARIABLES:
  NYPL_CORE_OBJECTS_BASE_URL: https://nypl-core-objects-mapping-production.s3.amazonaws.com/
  LOG_LEVEL: 'debug'
  S3_BUCKET: locations-mapping-production
  S3_LOCATIONS_FILE: locations.json
  REGION: us-east-1
  DRUPAL_API_BASE_URL: "https://drupal.nypl.org/jsonapi/node/library"
  TZ: America/New_York
  RC_ALERTS_URL: https://raw.githubusercontent.com/NYPL/locations-service/scc-3844/data/princeton-closures.csv
