PLAINTEXT_VARIABLES:
  NYPL_CORE_OBJECTS_BASE_URL: https://nypl-core-objects-mapping-production.s3.amazonaws.com/
  LOG_LEVEL: 'debug'
  S3_BUCKET: locations-mapping
  S3_LOCATIONS_FILE: locations.json
  REGION: us-east-1
